name = "lean-copilot-test"
version = "0.1.0"
defaultTargets = ["lean-copilot-test"]
moreLinkArgs = ["-L./.lake/packages/LeanCopilot/.lake/build/lib", "-lctranslate2"]

[[lean_lib]]
name = "LeanCopilotTest"

[[lean_lib]]
name = "test2"

[[lean_exe]]
name = "lean-copilot-test"
root = "Main"

[[require]]
name = "LeanCopilot"
git = "https://github.com/lean-dojo/LeanCopilot.git"
rev = "v4.28.0"

[[require]]
name = "cslib"
scope = "leanprover"
rev = "11b70e5"

